table product
	lineageTag: 1264b67b-6dd8-45bd-81fc-c4263d4ac292

	column product_key
		dataType: string
		lineageTag: 5b79e8b0-198d-4711-95a5-198867e46591
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column revenue_type
		dataType: int64
		formatString: 0
		lineageTag: 83e46106-bffe-49dd-917c-44cb438bdbc8
		summarizeBy: none
		sourceColumn: revenue_type

		annotation SummarizationSetBy = Automatic

	column product_level_1
		dataType: string
		lineageTag: abd7f36f-9ba1-4fe8-a1b4-1b556003ef61
		summarizeBy: none
		sourceColumn: product_level_1

		annotation SummarizationSetBy = Automatic

	column product_level_2
		dataType: string
		lineageTag: 2d27362a-760f-432e-a1c5-0b5c56cd11df
		summarizeBy: none
		sourceColumn: product_level_2

		annotation SummarizationSetBy = Automatic

	column product_dim_1
		dataType: string
		lineageTag: 87ce1698-4f43-4b31-b108-dcfcfc3e172b
		summarizeBy: none
		sourceColumn: product_dim_1

		annotation SummarizationSetBy = Automatic

	column product_dim_2
		dataType: string
		lineageTag: a2b25440-a849-4420-af6d-8eb0788d3746
		summarizeBy: none
		sourceColumn: product_dim_2

		annotation SummarizationSetBy = Automatic

	column product_dim_3
		dataType: string
		lineageTag: ae2685ce-806e-4df2-8b72-1c303311b57b
		summarizeBy: none
		sourceColumn: product_dim_3

		annotation SummarizationSetBy = Automatic

	column product_dim_4
		dataType: string
		lineageTag: 8d0ad786-5cfb-4215-a208-ec7600457605
		summarizeBy: none
		sourceColumn: product_dim_4

		annotation SummarizationSetBy = Automatic

	column product_dim_5
		dataType: string
		lineageTag: f5d71e51-9f3b-4f94-8e5d-1b1a9a86dbf7
		summarizeBy: none
		sourceColumn: product_dim_5

		annotation SummarizationSetBy = Automatic

	partition product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\DastagirAhmedS\Downloads\snowball_dataset.xlsx"), null, true),
				    product_Sheet = Source{[Item="product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_key", type text}, {"revenue_type", Int64.Type}, {"product_level_1", type text}, {"product_level_2", type text}, {"product_dim_1", type any}, {"product_dim_2", type any}, {"product_dim_3", type any}, {"product_dim_4", type any}, {"product_dim_5", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

